### ISSUE TITLE
MMOItems still not working

### ISSUE THREAD

**Issue by MidnightSugar** [divios/DailyShop#102]
Here is my updated config. It says java.lang.IllegalStateException: Not a JSON Object: [{"type":"SWORD"},{"id":"COMBAT_STAVE"}].

```
  MMOITEM:
    item:
      mmoItem:
        - type: SWORD
        - id: COMBAT_STAVE
    buyPrice:
      min: '20'
      max: '50'
    stock:
       type: GLOBAL
       amount: 5
    rarity: Common
    econ:
      name: vault
    confirm_gui: true

**Comment by divios** [comment]
```yaml
  MMOITEM:
    item:
      mmoItem:
        type: SWORD
        id: COMBAT_STAVE
    buyPrice:
      min: '20'
      max: '50'
    stock:
       type: GLOBAL
       amount: 5
    rarity: Common
    econ:
      name: vault
    confirm_gui: true
```

I'm quite retarded some times, the `-` are not necessary, sorry about that

**Comment by MidnightSugar** [comment]
Still not working. The example you provided just says "An item needs a material"

**Comment by divios** [comment]
Mmm but that only should happens if you are trying to add that as an item in the shop gui, not as a daily item

**Comment by MidnightSugar** [comment]
Could you explain further , I don't seem to understand. Am i putting it in the wrong location?

**Comment by divios** [comment]
Well, is not exactly the wrong location, but direct support for plugins like mmoitems is only available on the items fields. Example:

```yaml
id: blocks
timer: 86400
shop:
  title: blocks
  size: 45
  items: {}
items:
  MMOITEM:
    item:
      mmoItem:
        type: SWORD
          id: COMBAT_STAVE
    buyPrice:
      fixed: 30
```
This is one is correct, but this other will throw a error:

```yaml
id: blocks
timer: 86400
shop:
  title: blocks
  size: 45
  items: 
     MMOITEM:
        item:
           mmoItem:
              type: SWORD
              id: COMBAT_STAVE
        buyPrice:
           fixed: 30
items: {}
```

To clarify, custom items are only supported in the items field, which represents the daily items in the store, but not the items that represent the items in the shop gui.
