### ISSUE TITLE
Stock amount bug

### ISSUE THREAD

**Issue by Akiranya** [divios/DailyShop#115]
With the latest Dailyshop 3.7B, players can't sell items if the stock is 1 away from the full amount.

e.g.

With this shop item

```
  911fcd90-c40e-4b87-a801-5a348a8c5f8b:
    material: COPPER_INGOT
    buyPrice:
      fixed: 8
    sellPrice:
      fixed: 2.5
    stock:
      type: INDIVIDUAL
      amount: 1
      max: 129
      incrementOnSell: true
      allowSellOnMax: false
    rarity: Common
    econ:
      name: gemsEconomy
      currency: R
    confirm_gui: true
```

as you can see the `max` is set to 129. However, players can't sell more items if the stock is currently 128. This bug appears after I update dailyshop to 3.7B.
