### ISSUE TITLE
Ability to have a starting stock, and a max stock.

### ISSUE THREAD

**Issue by refractored** [divios/DailyShop#163]
It'd be nice to have this feature because atm you cant sell items when the shop resets because its already at the max stock.

**Comment by divios** [comment]
Hi! You can already do that. Here is an exmaple:

```yaml
Diamond:
  material: DIAMOND
  buyPrice:
    fixed: 30
  stock:
    type: GLOBAL
    amount: 4
    max: 10
    incrementOnSell: true
    allowSellOnMax: false
```

Here, diamond will have a start stock of 4, and the max amount of the stock is 10.You can also specify whether the stock should increase when items are sold and also whether you want to allow items to be sold even if the stock is at maximum.
