### ISSUE TITLE
Remove lore symbol

### ISSUE THREAD

**Issue by AlternativeSoap** [divios/DailyShop#80]
Hi, is it possible to fix lore when adding an item with a lore?

Whenever I add an item with a lore, it goes purple and I need to go into the file to change some symbols that replaced "&"...

**Comment by AlternativeSoap** [comment]
That is weird, because they go colors.

Got an item with red color, but it changes the symbol "&" to a diamond look-a-like

**Comment by AlternativeSoap** [comment]
"    - '�a?�7 Radiation level: �cVERY HIGH'"
"    - �8? �4Hazmat Suit required!"

Example it removes & and replace it with this.

**Comment by AlternativeSoap** [comment]
And also

another issue I've got...

You can't change "Vault" symbol to example "$"

**Comment by AlternativeSoap** [comment]
Exactly! It will change it to those symbols, so it's not exact the same item anymore. So yes, if you want to do that I'll be happy.

**Comment by divios** [comment]
> And also
> 
> another issue I've got...
> 
> You can't change "Vault" symbol to example "$"

This is because you have to change Vault to vault and it will work

**Comment by divios** [comment]
PD: my bad, the vault_name is deprecated and I forgot to delete in from settings.yml, to change vault's name you should use the field Econ-names

```yaml
settings:
  prefix: "&e&lDailyShop &7> "
  debug: false
  default-buy-price: 500.0
  default-sell-price: 20
  default_timer: 86400
  integer-bal: true
  econ-names:
    vault: "$"
```
